config/routes.rb
Rails.application.routes.draw do
  get 'crud', to: "employee_crud#index"
  get 'crud/:id', to: "employee_crud#index"
  get 'reports', to: "reports#index"
  get 'admin', to: "home#index"
  get 'branches', to: "branches#index"
  post 'admin', to: "home#login"
  post 'logout', to: "employee_crud#logout"
  post 'create_employee', to: "employee_crud#create"
  post 'edit_employee', to: "employee_crud#edit"
  post 'disable_employee', to: "employee_crud#disable"
  post 'check', to: "employee#check"
  post 'create_branch', to: "branches#create"
  post 'edit_branch', to: "branches#edit"
  post 'delete_branch', to: "branches#delete"
  root "employee#employee"
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord
end

app/models/check.rb
class Check < ApplicationRecord
    
end

app/models/employee.rb
class Employee < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include ApplicationHelper
  helper_method :logged_in?
  helper_method :current_admin
  private 

  def require_login
    unless logged_in?
      redirect_to admin_path, notice: 'You have to be logged in'
    end
  end
  
end

app/controllers/branch_crud_controller.rb
class BranchCrudController < ApplicationController
  before_action :require_login
  def index
    @branches = Branch.all
  end

  def new
    @branch = Branch.new
  end

  def create
    @branch = Branch.new(branches_params)
    if @branch.save
      redirect_to branches_path
    else
      render :new
    end
  end

  def edit
    @branch = Branch.find(params[:id])
    if @branch.update(:store=>params[:store],:name=>params[:name],:address=>params[:address])
      redirect_to branches_path
    end
  end
  
  def delete
    @branch = Branch.find(params[:id])
    if @branch.destroy
      redirect_to branches_path
    end
  end

  private
  
  def branches_params
    params.permit(:store,:name,:address)
  end
  
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :require_login
  def index
    @branches = Branch.all
  end

  def new
    @branch = Branch.new
  end

  def create
    @branch = Branch.new(branches_params)
    if @branch.save
      redirect_to branches_path
    else
      render :new
    end
  end

  def edit
    @branch = Branch.find(params[:id])
    redirect_to branches_path if @branch.update(store: params[:store], name: params[:name],
    address: params[:address])
  end
  
  def delete
    @branch = Branch.find(params[:id])
    redirect_to branches_path if @branch.destroy
  end

  private
  
  def branches_params
    params.permit(:store,:name,:address)
  end
  
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
  def employee
    @branches = Branch.all
  end
  
  def check
    @employee = Employee.find_by(privateNumber: params[:privateNumber])
    if !! @employee && @employee.branches_id == params[:branches_id].to_i
      params[:check] = helpers.check_value(params[:checkin])
      params[:date] = Time.now.strftime("%d/%m/%Y")
      params[:hour] = Time.now.strftime("%H:%M")
      params[:employees_id] = @employee.id
      @check = Check.new(check_params)
      redirect_to root_path, notice: helpers.check_save(@check)
    else
      redirect_to root_path, alert: 'PrivateNumber does not exist or does not exists in that branch'
    end
    
  end
  
  private

  def check_params
    params.permit(:date, :hour, :check, :employees_id)
  end

end

app/controllers/employee_crud_controller.rb
  class EmployeeCrudController < ApplicationController
    before_action :require_login
  
    def index
      if params[:id] != nil
        @employees = Employee.where(branches_id:params[:id])
      else
        @employees = Employee.all
      end
      @branches = Branch.all
    end
    
    def logout
      session[:admin_id] = nil
      redirect_to admin_path
    end
  
    def new
      @emp = Employee.new
    end
  
    def create
      @emp = Employee.new(employee_params)
      if @emp2 = Employee.find_by(privateNumber:params[:privateNumber])
        redirect_to crud_path, notice: 'The private number already exists'
      else
        if @emp.save
          redirect_to crud_path
        else
          render :new
        end
      end
    end
  
    def edit
      @emp = Employee.find(params[:id])
      if @emp.update(:privateNumber=> params[:privateNumber], :employeeNumber=>params[:employeeNumber],
        :email=>params[:email],:name=>params[:name],
        :position=>params[:position],:status=>params[:status],:branches_id=>params[:branches_id])
        redirect_to crud_path
      end
    end
  
    def disable
      @emp = Employee.find(params[:id])
      if @emp.status == true
        if @emp.update(:status=>0)
          redirect_to crud_path
        end
      else
        if @emp.update(:status=>1)
          redirect_to crud_path
        end
      end
    end
  
    private 
  
    def employee_params
      params.permit(:privateNumber, :employeeNumber, :email, :name, :position, :status, :branches_id)
    end
  
  end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def login
    @admin = Admin.find_by(user: params[:user])
    if !!@admin && @admin.authenticate(params[:password])
      session[:admin_id] = @admin.id
      redirect_to crud_path
    else
      redirect_to admin_path, notice: 'Wrong user or password'
    end
  end
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :require_login
  def index
    @checks = Check.all
    @checkin = Check.where(check:true)
    @checkout = Check.where(check:false)
    @employees = Employee.all
    @checkin_avg = helpers.avg_time(@checkin)
    @checkout_avg = helpers.avg_time(@checkout)
    @absences = helpers.absences(@checkin,@employees)
    @atendance = Check.where(check:true).group(:date).count
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def logged_in?
    !!session[:admin_id]
  end

end

app/helpers/employee_helper.rb
module EmployeeHelper

  def check_value(check)
    check ? 1 : 0
  end 

  def check_save(check)
    if check.save
      message = params[:check] == 1 ? 'Successful check in' : 'Successful check out'
    else
      'Failed to check'
    end
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper

    def checkEmployee(idEmployee)
        puts(Time);
        
         
        
        
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reports_helper.rb
module ReportsHelper

  def avg_time(checks)
    if checks.size > 0 
      avg = checks.size 
      avg_minutes = checks.map do |p|
        hour, minute = p.hour.strftime('%H:%M').to_s.split(':')
        total_minutes = hour.to_i * 60 + minute.to_i
      end.inject(:+)/avg
      "#{avg_minutes/60}:#{avg_minutes%60}"
    end
  end

  def absences(checkins,employees)
    absences = Array.new
    employees.each do |e|
      count = 0
      checkins.each do |c|
        if e.id == c.employees_id
          count +=1
        end
      end
      if count == 0
        absences.push(e)
      end
    end
    absences
  end
  

end

app/views/employee/employee.html.erb
	<div class ="container">
		<div class ="row justify-content-end">
			<div class ="col-1">
				<form action="admin" method=get>
					<button type="submit" class="btn btn-primary">Admin</button>
				</form>
			</div>
		</div>
	</div>

	<div class="container ">
		<div class ="row align-items-center d-flex">
			<div class ="col-6">
				<form method="post" action="check">
					<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
					<div class="form-group">
						<input type="text" class="form-control" id="privateNumber" name="privateNumber" placeholder="Private number">
					</div>
					<div class="input-group form-group">  
            <select class="form-select form-control" id="branches_id" name="branches_id" aria-label="Default select example">
              <% @branches.each do |branch|%>
                  <option value="<%= branch.id %>"><%= branch.name %></option>
              <% end %>
            </select>
        	</div>
					<button type="submit" id= "checkin" name="checkin" class="btn btn-success check_in">Check In</button>
					<button type="submit" id ="checkout" name ="checkout" class="btn btn-danger check_out">Check Out</button>
				</form>
				<p class="text-success"id="notice"><%= notice %></p>
				<p class="text-danger"id="alert"><%= alert %></p>
			</div>
			<div class ="col-6 align-self-center">
				<div class="container container-employee">
					<div class="clock">
						<div id="date" class="date box"></div>
						<div class="clock-face">
							<div class="marker twelve"></div>
							<div class="marker three"></div>
							<div class="marker six"></div>
							<div class="marker nine"></div>
							<div id="minute-hand" class="hand minute-hand"></div>
							<div id="hour-hand" class="hand hour-hand"></div>
							<div id="second-hand" class="hand second-hand"></div>
							<div id="centre" class="centre"></div>
							<div id="digital-time" class="digital-time box"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
<%= javascript_pack_tag 'employee' %>

app/views/employee_crud/index.html.erb
<!DOCTYPE html>
  <html>
  <head>
  
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="<%= crud_path %>">Employees</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= reports_path %>">Reports</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= branches_path %>">Branches</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class = "container">
      <div class = "row justify-content-end " >
        <div class ="col-1" >
          <form action="/logout" method="post">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <div class="dropdown show">
              <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"></path>
                  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"></path>
                </svg>
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <input type="submit" value ="Log out" class="dropdown-item" >
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>

    <div class = "container mt-5">
      <div class = "row justify-content-center">
        <div class ="col-10" >
            <div class="input-group justify-content-center">
                <div class="dropdown show">
                  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Company branch
                  </a>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <form action="/crud" method="get">
                      <input type="submit" value ="No branches" class="dropdown-item" >
                    </form>
                  <% @branches.each do |branch|%>
                    <form action="/crud/<%= branch.id %>" method="get">
                      <input type="submit" name="<%= branch.id %>" id="<%= branch.id %>" value ="<%= branch.name %>" class="dropdown-item" >
                    </form>
                  <% end %>
                </div>
              </div>
              <button type="button" class="btn btn-success ml-3" data-toggle="modal" data-target="#addEmployee">
                Add
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-square-fill" viewBox="0 0 16 16">
                  <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z"></path>
                </svg>
              </button>
            </div>
        </div>
      </div>
    </div>

    <p class="text-danger" id="notice"><%= notice %></p>

    <div class="container mt-3">
      <div class ="row justify-content-center">
        <div class="col-12">
          <table class="table table-dark table-hover">
            <thead>
              <tr>
                <th scope="col">Em#</th>
                <th scope="col">Name</th>
                <th scope="col">Position</th>
                <th scope="col">Email</th>
                <th scope="col">Priv#</th>
                <th scope="col">status</th>
                <th scope="col">Edit</th>
                <th scope="col">Disable</th>
              </tr>
            </thead>
            <tbody>
              <% @employees.each do |employee|%>
                <tr>
                  <th scope="row"><%= employee.employeeNumber%></th>
                  <td><%= employee.name%></td>
                  <td><%= employee.position%></td>
                  <td><%= employee.email %></td>
                  <td><%= employee.privateNumber%></td>
                  <td class="<%= employee.status ?  "text-success": "text-danger" %>"><%= employee.status ?  "Enabled": "Disabled" %></td>
                  <td>
                    <button type="button" id="<%= employee.id %>" data-toggle="modal" data-target="#editEmployee<%= employee.id %>" class="btn btn-success">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                        <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"></path>
                      </svg>
                    </button>
                  </td>
                  <td>
                    <form method="post" action="/disable_employee">
                      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                      <input type="hidden" name ="id" value="<%= employee.id %>" id ="id" class="form-control" placeholder="privateNumber">
                      <button type="submit" class="btn btn-danger">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-x" viewBox="0 0 16 16">
                        <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                        <path fill-rule="evenodd" d="M12.146 5.146a.5.5 0 0 1 .708 0L14 6.293l1.146-1.147a.5.5 0 0 1 .708.708L14.707 7l1.147 1.146a.5.5 0 0 1-.708.708L14 7.707l-1.146 1.147a.5.5 0 0 1-.708-.708L13.293 7l-1.147-1.146a.5.5 0 0 1 0-.708z"/>
                      </svg>  
                    </button>
                    </form>
                  </td>
                </tr>
                <div class="modal" id="editEmployee<%= employee.id %>" tabindex="-1" role="dialog">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title text-dark">Edit employee</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <form action="/edit_employee" method="post">
                          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                            <div class="input-group form-group">
                              <input type="hidden" name ="id" value="<%= employee.id %>" id ="id" class="form-control" placeholder="privateNumber">
                            </div>
                            <div class="input-group form-group">
                              <input type="text" name ="privateNumber" value="<%= employee.privateNumber %>" id ="privateNumber" class="form-control" placeholder="privateNumber">
                            </div>
                            <div class="input-group form-group">
                              <input type="text" name="employeeNumber" value="<%= employee.employeeNumber %>" id="employeeNumber" class="form-control" placeholder="employeeNumber">
                            </div>
                            <div class="input-group form-group">
                              <input type="email" name="email" value="<%= employee.email %>" id="email" class="form-control" placeholder="email">
                            </div>
                            <div class="input-group form-group">
                              <input type="text" name="name" id="name" value="<%= employee.name %>" class="form-control" placeholder="name">
                            </div>
                            <div class="input-group form-group">
                              <input type="text" name="position" id="position" value="<%= employee.position %>" class="form-control" placeholder="position">
                            </div>
                            <div class="input-group form-group">
                              <select class="form-select form-control" name="status" id="status">
                                <option value="1">Activo</option>
                                <option value="0">Inactivo</option>
                              </select>
                            </div>
                            <div class="input-group form-group">  
                                <select class="form-select form-control" id="branches_id" name="branches_id" aria-label="Default select example">
                                  <% @branches.each do |branch|%>
                                  <option value="<%= branch.id %>"><%= branch.name %></option>
                                <% end %>
                                </select>
                            </div>
                            <div class="form-group">
                              <input type="submit" value="Save" class="btn btn-success float-right">
                            </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>

    <div class="modal" id="addEmployee" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title text-dark">Add new employee</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form action="/create_employee" method="post">
              <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                <div class="input-group form-group">
									<input type="text" name ="privateNumber" id ="privateNumber" class="form-control" placeholder="privateNumber">
								</div>
								<div class="input-group form-group">
									<input type="text" name="employeeNumber" id="employeeNumber" class="form-control" placeholder="employeeNumber">
								</div>
                <div class="input-group form-group">
									<input type="email" name="email" id="email" class="form-control" placeholder="email">
								</div>
                <div class="input-group form-group">
									<input type="text" name="name" id="name" class="form-control" placeholder="name">
								</div>
                <div class="input-group form-group">
									<input type="text" name="position" id="position" class="form-control" placeholder="position">
								</div>
                <div class="input-group form-group">
                  <select class="form-select form-control" name="status" id="status">
                    <option value="1">Activo</option>
                    <option value="0">Inactivo</option>
                  </select>
								</div>
                <div class="input-group form-group">  
                    <select class="form-select form-control" id="branches_id" name="branches_id" aria-label="Default select example">
                      <% @branches.each do |branch|%>
                      <option value="<%= branch.id %>"><%= branch.name %></option>
                    <% end %>
                    </select>
								</div>
								<div class="form-group">
									<input type="submit" value="Add" class="btn btn-success float-right">
								</div>
            </form>
          </div>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/employees/index.html.erb
<h1>Employees#index</h1>
<p>Find me in app/views/employees/index.html.erb</p>

app/views/home/index.html.erb
	<html>
		<body>
			<div class ="container">
				<div class="login-container">
					<div class="d-flex justify-content-center h-100">
						<div class="card">
							<div class="card-header">
								<h3>Sign In</h3>
							</div>
							<div class="card-body">
								<form action="admin" accept-charset="UTF-8" method="POST">
									<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
									<div class="input-group form-group">
										<div class="input-group-prepend">
											<span class="input-group-text"><i class="fas fa-user"></i></span>
										</div>
										<input type="text" name ="user" id ="user"class="form-control" placeholder="username">
									</div>
									<div class="input-group form-group">
										<div class="input-group-prepend">
											<span class="input-group-text"><i class="fas fa-key"></i></span>
										</div>
										<input type="password" name="password" id="password" class="form-control" placeholder="password">
									</div>
									<div class="form-group">
										<input type="submit" value="Log in" class="btn btn-light float-right login_btn">
									</div>
								</form>
								<p class="text-danger"id="notice"><%= notice %></p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</body>
	</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RelojChecador</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reports/index.html.erb
  <head>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
  </head>
    <nav class="navbar navbar-expand-lg navbar-dark">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="<%= crud_path %>">Employees</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="<%= reports_path %>">Reports</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= branches_path %>">Branches</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class ="container col-8 table-wrapper-scroll-y my-custom-scrollbar">
    <table class="table table-dark">
      <thead>
        <tr>
          <th scope="col">Day</th>
          <th scope="col">Atendance</th>
        </tr>
      </thead>
      <tbody>
        <% @atendance.each do |a| %>
          <tr>
            <th scope="row"><%= a[0] %></th>
            <td><%= a[1] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
    <div class ="container col-9">
        <div class ="d-flex">
          <div class ="container-check mr-auto p-2">
          <h5 >Average check in time: <span class="badge bg-secondary"><%= @checkin_avg %></span></h5>
          <h5 >Average check out time: <span class="badge bg-secondary"><%= @checkout_avg %></span></h5>
          </div> 
          <!-- Button trigger modal -->
          <div class ="container-report p-2">
          <button type="button" class="btn btn-danger btn-report" data-toggle="modal" data-target="#exampleModal">
            Absence report
          </button>
          </div>
        </div> 

          <!-- Modal -->
          <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title text-dark" id="exampleModalLabel">Employee absence</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <% @absences.each do |a| %>
                    <p class="text-danger"><span>Name: </span><%= a.name %> <span>PN: </span><%= a.privateNumber %></p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div> 